AWSTemplateFormatVersion: '2010-09-09'
Description: Create AWS Cognito User Pool for Amazon Q Business proof-of-concept

Resources:
  PreTokenGenLambdaExecRole:
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W11
            reason: Role for Cognito Pre-token generation Lambda
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  
  PreTokenGenLambda:
    Type: AWS::Lambda::Function
    DependsOn:
      - PreTokenGenLambdaExecRole
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W92
            reason: Lambda used by CFN Stack Creation for managing custom resources
          - id: W89
            reason: Lambda used by CFN Stack Creation for managing custom resources. VPC not required
    Properties:
      Handler: index.handler
      Runtime: python3.11
      Timeout: 300
      Description: Create IDC Local Instance
      Role: !GetAtt PreTokenGenLambdaExecRole.Arn
      Code:
        ZipFile: |
          import json
          def handler(event, context):
              event["response"] = {
                  "claimsAndScopeOverrideDetails": {
                      "idTokenGeneration": {
                          "claimsToAddOrOverride": {
                              "principal_tags": {
                                  "Email": [event['request']['userAttributes']['email']]
                              }
                          },
                      },
                      "accessTokenGeneration": {}
                  }
              }
              return event

  UserPool:
    Type: AWS::Cognito::UserPool
    DependsOn:
      - PreTokenGenLambda
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: F78
            reason: CFN intended for proof-of-concept. SMS may not be available for MFA yet.
    Properties:
      UserPoolName: !Sub ${AWS::StackName}-user-pool
      UserPoolAddOns:
        AdvancedSecurityMode: AUDIT
      LambdaConfig:
        PreTokenGenerationConfig:
          LambdaArn: !GetAtt PreTokenGenLambda.Arn
          LambdaVersion: V2_0
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      MfaConfiguration: "OFF"
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireNumbers: true

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: !Sub ${AWS::StackName}-client
      GenerateSecret: true
      ExplicitAuthFlows:
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      PreventUserExistenceErrors: "ENABLED"
      AllowedOAuthFlows: 
        - code
      AllowedOAuthFlowsUserPoolClient: True
      AllowedOAuthScopes:
        - openid
        - email
        - profile
      CallbackURLs:
        - !Ref AppCallbackURL
      LogoutURLs:
        - !Ref AppLogoutURL
      SupportedIdentityProviders:
        - COGNITO
    DependsOn:
      - UserPool

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      UserPoolId: !Ref UserPool
      Domain: !Join
        - '-'
        - - !Ref AWS::StackName
          - !Select [1, !Split ['-', !Select [2, !Split ['/', !Ref AWS::StackId]]]]
    DependsOn:
      - UserPool

Parameters:
  AppCallbackURL:
    Type: String
    Default: 'http://localhost:8080/authorization-code/callback'
    Description: Application url for Cognito to callback after authentication
  AppLogoutURL:
    Type: String
    Default: 'http://localhost:8080/logout'
    Description: Application url to logout user

Outputs:
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool
  UserPoolDomainName:
    Description: Cognito User Pool Domain Name
    Value: !Sub '${UserPoolDomain}.auth.${AWS::Region}.amazoncognito.com'
  IssuerURL:
    Description: Issuer URL
    Value: !GetAtt UserPool.ProviderURL
  OAuthURL:
    Description: OAuth URL
    Value: !Sub 'https://${UserPoolDomain}.auth.${AWS::Region}.amazoncognito.com'
  ClientId:
    Description: Client ID
    Value: !GetAtt UserPoolClient.ClientId
  ClientSecret:
    Description: Client Secret
    Value: !GetAtt UserPoolClient.ClientSecret
